import { mkdir, writeFile } from "node:fs/promises";
import { dirname } from "node:path";
import { parseUnifiedDiff, reviewPatch, type Finding, type ReviewDecision } from "../../../packages/product-runtime/src/index.js";
import { nanoidPilotPolicy, pLimitPilotPolicy, type RealPrPilotCase } from "./product-real-pr-pilot-fixtures.js";

type GitHubPullRequest = {
  number: number;
  title: string;
  body: string | null;
  html_url: string;
  base: { ref: string };
  head: { ref: string };
  merged_at: string | null;
  changed_files: number;
};

const args = parseArgs(process.argv.slice(2));
if (args.help === "true" || args.h === "true") {
  printHelp();
  process.exit(0);
}

const repo = args.repo ?? "ai/nanoid";
const numbers = parseNumbers(requireArg(args, "prs"));
const outPath = args.out ?? "examples/product-runtime/real-pr-fixtures/nanoid-github-prs.draft.json";
const policy = selectPolicy(args.policy ?? "nanoid");
const cases: RealPrPilotCase[] = [];

for (const number of numbers) {
  // Gerçek PR metadatası ve diff ayrı endpointlerden gelir; fixture hem insan
  // incelemesi hem de deterministik pilot için ikisini birlikte saklar.
  const [pullRequest, diff] = await Promise.all([
    fetchJson<GitHubPullRequest>(`https://api.github.com/repos/${repo}/pulls/${number}`),
    fetchText(`https://github.com/${repo}/pull/${number}.diff`)
  ]);
  // Varsayılan mod bilimsel ground truth üretmez. Mevcut runtime kararını
  // taslak label yapar; insan reviewer daha sonra bunu düzeltebilir.
  const review = reviewPatch({
    task: createTask(repo, pullRequest),
    diff: parseUnifiedDiff(diff),
    policy
  });
  const findingCategories = Array.from(new Set(review.findings.map((finding) => finding.category))).sort();
  const expectedDecision = selectExpectedDecision(args["label-mode"] ?? "runtime-draft", review.decision);

  cases.push({
    id: `${repo.replace(/[^a-z0-9]+/gi, "-").toLowerCase()}-pr-${pullRequest.number}`,
    family: toFamily(expectedDecision),
    source: {
      repository: repo,
      pullRequest: `#${pullRequest.number}`,
      baseRef: pullRequest.base.ref,
      headRef: pullRequest.head.ref,
      note: `Imported from ${pullRequest.html_url}. merged_at=${pullRequest.merged_at ?? "not_merged"} changed_files=${pullRequest.changed_files}`
    },
    task: createTask(repo, pullRequest),
    policy,
    diff,
    reviewerNotes: [
      `DRAFT_LABEL: generated by product-github-pr-import using label-mode=${args["label-mode"] ?? "runtime-draft"}.`,
      "A human reviewer must verify expectedDecision and expectedFindingCategories before using this as external validation.",
      `PR title: ${pullRequest.title}`
    ],
    expectedDecision,
    expectedFindingCategories: findingCategories
  });
}

await mkdir(dirname(outPath), { recursive: true });
await writeFile(outPath, `${JSON.stringify(cases, null, 2)}\n`);

console.log(JSON.stringify({
  ok: true,
  repo,
  prCount: cases.length,
  outPath,
  labelMode: args["label-mode"] ?? "runtime-draft",
  imported: cases.map((testCase) => ({
    id: testCase.id,
    decision: testCase.expectedDecision,
    findings: testCase.expectedFindingCategories
  }))
}, null, 2));

function createTask(repo: string, pullRequest: GitHubPullRequest) {
  const authority = inferAuthority(pullRequest);

  return {
    id: `${repo.replace(/[^a-z0-9]+/gi, "-").toLowerCase()}-pr-${pullRequest.number}`,
    title: pullRequest.title,
    description: [
      `Imported GitHub PR: ${pullRequest.html_url}`,
      `Title: ${pullRequest.title}`,
      authority,
      pullRequest.body ? `Body: ${pullRequest.body.slice(0, 2_000)}` : "Body: (empty)"
    ].join("\n"),
    authorityFacts: [authority]
  };
}

function inferAuthority(pullRequest: GitHubPullRequest): string {
  const text = `${pullRequest.title}\n${pullRequest.body ?? ""}`.toLowerCase();
  // Buradaki authority çıkarımı bilinçli olarak basit tutulur. Amaç PR'ı
  // mükemmel anlamak değil, reviewer'ın düzeltebileceği ilk taslak bağlamı kurmak.
  if (text.includes("non-secure")) return "Authority: non-secure approved this imported PR draft.";
  if (text.includes("map method") || text.includes("iterable") || text.includes("limit function") || text.includes("concurrency limit") || text.includes("clear the queue")) {
    return "Authority: core approved this imported PR draft.";
  }
  if (text.includes("benchmark")) return "Authority: performance approved this imported PR draft.";
  if (text.includes("performance") || text.includes("faster") || text.includes("optimi")) return "Authority: performance approved this imported PR draft.";
  if (text.includes("release") || text.includes("version")) return "Authority: release maintenance update is approved.";
  if (text.includes("dependency") || text.includes("dependencies") || text.includes("bump ")) return "Authority: dependency maintenance update is approved.";
  if (text.includes("types") || text.includes("typescript") || text.includes("jsdoc")) return "Authority: types approved this imported PR draft.";
  if (text.includes("readme") || text.includes("docs") || text.includes("translation")) return "Authority: docs approved this imported PR draft.";
  if (text.includes("cli") || text.includes("bin")) return "Authority: developer-tools approved this imported PR draft.";
  return "Authority: core approved this imported PR draft.";
}

function selectExpectedDecision(labelMode: string, decision: ReviewDecision): ReviewDecision {
  if (labelMode === "runtime-draft") return decision;
  if (isReviewDecision(labelMode)) return labelMode;
  throw new Error(`Unknown --label-mode value: ${labelMode}`);
}

function toFamily(decision: ReviewDecision): RealPrPilotCase["family"] {
  if (decision === "approve") return "expected_pass";
  if (decision === "remask_required") return "expected_repair";
  if (decision === "human_review_required") return "expected_human_review";
  return "expected_block";
}

function selectPolicy(value: string) {
  if (value === "nanoid") return nanoidPilotPolicy;
  if (value === "p-limit") return pLimitPilotPolicy;
  throw new Error(`Unknown --policy value: ${value}`);
}

async function fetchJson<T>(url: string): Promise<T> {
  const response = await fetch(url, { headers: githubHeaders() });
  if (!response.ok) throw new Error(`GitHub request failed ${response.status}: ${url}`);
  return await response.json() as T;
}

async function fetchText(url: string): Promise<string> {
  const response = await fetch(url, { headers: githubHeaders() });
  if (!response.ok) throw new Error(`GitHub request failed ${response.status}: ${url}`);
  return await response.text();
}

function githubHeaders(): Record<string, string> {
  const headers: Record<string, string> = {
    "Accept": "application/vnd.github+json",
    "User-Agent": "bounded-dllm-agent-lab"
  };
  if (process.env.GITHUB_TOKEN) headers.Authorization = `Bearer ${process.env.GITHUB_TOKEN}`;
  return headers;
}

function parseNumbers(value: string): number[] {
  return value.split(",").map((part) => Number(part.trim())).filter((number) => Number.isInteger(number));
}

function parseArgs(values: string[]): Record<string, string> {
  const parsed: Record<string, string> = {};

  for (let index = 0; index < values.length; index += 1) {
    const value = values[index];
    if (!value.startsWith("--")) continue;
    const key = value.slice(2);
    const next = values[index + 1];

    if (!next || next.startsWith("--")) {
      parsed[key] = "true";
      continue;
    }

    parsed[key] = next;
    index += 1;
  }

  return parsed;
}

function requireArg(args: Record<string, string>, key: string): string {
  const value = args[key];
  if (!value) throw new Error(`Missing required argument --${key}`);
  return value;
}

function isReviewDecision(value: string): value is ReviewDecision {
  return value === "approve" ||
    value === "refuse" ||
    value === "reject" ||
    value === "remask_required" ||
    value === "human_review_required";
}

function printHelp(): void {
  console.log(`GitHub PR Fixture Import

Usage:
  npm run product:github-pr-import -- --repo ai/nanoid --prs 600,586 --out examples/product-runtime/real-pr-fixtures/nanoid-github-prs.draft.json

Options:
  --repo <owner/name>          GitHub repository. Default: ai/nanoid
  --prs <numbers>             Comma-separated PR numbers. Required.
  --out <path>                Output JSON fixture path.
  --policy <name>             Policy profile: nanoid, p-limit. Default: nanoid
  --label-mode <value>        runtime-draft or fixed ReviewDecision. Default: runtime-draft
  --help                      Show this help.
`);
}
