'use strict';
const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const cp = require('node:child_process');
const crypto = require('node:crypto');
const { parseSessionId, sessionPath, assertUnusedSession, observationSlots, assertPreflightBinding, preflightRecord, assertObservationAvailable } = require('./session-identity.cjs');
const root = __dirname;
const manifest = JSON.parse(fs.readFileSync(path.join(root, 'benchmark-manifest.json')));
const frozen = JSON.parse(cp.execFileSync('git', ['show', 'eb0b501ba6d106730ba15c0e7f3dc3a5e4f5b496:research/bounded-vs-codex-robustness-v1/benchmark-manifest.json'], { encoding: 'utf8' }));
const { sessionId: oldSession, ...definition } = frozen;
assert.deepEqual(manifest, definition);
assert.deepEqual(manifest.tasks, frozen.tasks);
assert.equal(Object.hasOwn(manifest, 'sessionId'), false);
const canonical = x => Array.isArray(x) ? `[${x.map(canonical).join(',')}]` : x && typeof x === 'object' ? `{${Object.keys(x).sort().map(k => `${JSON.stringify(k)}:${canonical(x[k])}`).join(',')}}` : JSON.stringify(x);
for (const task of manifest.tasks) {
  const { taskHash, ...content } = task;
  assert.equal(taskHash, `sha256:${crypto.createHash('sha256').update(canonical(content)).digest('hex')}`);
  assert.equal(taskHash, frozen.tasks.find(t => t.taskId === task.taskId).taskHash);
  assert.equal(task.model, manifest.model); assert.equal(task.reasoning, manifest.reasoning);
  assert.equal(task.sourceHead, manifest.sourceHead);
  assert.equal(task.policy.retry + task.policy.repair + task.policy.apply, 0);
}
assert.deepEqual(manifest.tasks.map(t => t.difficulty), ['easy','medium_a','medium_b','medium_c','hard']);
assert.deepEqual(manifest.tasks.map(t => t.order), [['normal','bounded'],['bounded','normal'],['normal','bounded'],['bounded','normal'],['normal','bounded']]);
const a = 'robustness-v1-2026-09-29-r5', b = 'robustness-v1-2026-09-29-r6';
assert.equal(parseSessionId(['--session-id', a]), a);
assert.equal(parseSessionId([`--session-id=${a}`]), a);
for (const args of [[], ['--session-id'], ['--session-id', '../bad'], ['--session-id', 'robustness-v1-2026-09-28'], ['--session-id', a, '--session-id', b]]) assert.throws(() => parseSessionId(args));
const slotsA = observationSlots(manifest, a), slotsB = observationSlots(manifest, b);
assert.equal(slotsA.length, 10); assert.equal(new Set(slotsA.map(x => x.observationId)).size, 10);
assert.equal(slotsA[0].obsId, 'R1-normal'); assert.equal(slotsA[9].obsId, 'R5-bounded');
assert.deepEqual(slotsA.map(x => x.taskHash), slotsB.map(x => x.taskHash));
assert.ok(slotsA.every((x, i) => x.observationId !== slotsB[i].observationId));
const tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'robustness-session-test-'));
try {
  const historical = ['robustness-v1-2026-09-28', 'robustness-v1-2026-09-28-r2', 'robustness-v1-2026-09-28-r3', 'robustness-v1-2026-09-28-r4'];
  for (const id of historical) fs.mkdirSync(path.join(tmp, id));
  const oldBefore = historical.map(id => fs.readdirSync(path.join(tmp, id)));
  for (const id of historical.slice(1)) assert.throws(() => assertUnusedSession(tmp, id), /already exists/);
  assert.equal(assertUnusedSession(tmp, a), sessionPath(tmp, a));
  assert.deepEqual(historical.map(id => fs.readdirSync(path.join(tmp, id))), oldBefore);
  const dir = sessionPath(tmp, a); fs.mkdirSync(dir);
  const firstObsDir = path.join(dir, 'observations', 'R1-normal');
  assert.doesNotThrow(() => assertObservationAvailable([], slotsA, 'R1-normal', firstObsDir));
  assert.throws(() => assertObservationAvailable([], slotsA, 'R1-bounded', firstObsDir), /order/);
  const completed = [{ sessionId: a, observationId: slotsA[0].observationId, obsId: 'R1-normal', state: 'completed' }];
  assert.doesNotThrow(() => assertObservationAvailable(completed, slotsA, 'R1-bounded', path.join(dir, 'observations', 'R1-bounded')));
  assert.throws(() => assertObservationAvailable(completed, slotsA, 'R1-normal', firstObsDir), /consumed/);
  assert.throws(() => assertObservationAvailable([{ ...completed[0], state: 'reserved' }], slotsA, 'R1-bounded', firstObsDir), /consumed/);
  fs.mkdirSync(path.dirname(firstObsDir)); fs.mkdirSync(firstObsDir);
  assert.throws(() => assertObservationAvailable([], slotsA, 'R1-normal', firstObsDir), /consumed/);
  fs.rmSync(firstObsDir, { recursive: true }); fs.rmdirSync(path.dirname(firstObsDir));
  const head = 'f'.repeat(40);
  const pre = preflightRecord(a, 'initial', { ok: true, providerCalls: 0, benchmarkHead: head, sessionId: b });
  const post = preflightRecord(a, 'post-push', { ok: true, providerCalls: 0, benchmarkHead: head });
  assert.equal(pre.sessionId, a);
  fs.writeFileSync(path.join(dir, 'preflight.json'), JSON.stringify(pre));
  fs.writeFileSync(path.join(dir, 'post-push-preflight.json'), JSON.stringify(post));
  assertPreflightBinding(pre, post, a, head);
  assert.throws(() => assertPreflightBinding(pre, post, b), /mismatch/);
  assert.throws(() => assertPreflightBinding(pre, { ...post, sessionId: b }, a), /mismatch/);
  assert.throws(() => assertUnusedSession(tmp, a), /already exists/);
  const runner = (args) => cp.spawnSync(process.execPath, [path.join(root, 'run-observation.cjs'), ...args], { env: { ...process.env, ROBUSTNESS_RESULT_ROOT: tmp }, encoding: 'utf8' });
  const inspect = runner(['--inspect-session', '--session-id', a]);
  assert.equal(inspect.status, 0, inspect.stderr);
  const output = JSON.parse(inspect.stdout);
  assert.equal(output.sessionId, a); assert.equal(output.providerCalls, 0);
  assert.equal(output.availableObservationIds.length, 10);
  assert.equal(output.model, manifest.model); assert.equal(output.reasoning, manifest.reasoning); assert.equal(output.sourceHead, manifest.sourceHead);
  assert.notEqual(runner(['--inspect-session', '--session-id', b]).status, 0);
  assert.notEqual(runner(['--inspect-session', '--session-id', '../bad']).status, 0);
  fs.writeFileSync(path.join(dir, 'ledger.json'), JSON.stringify([{ sessionId: a, observationId: slotsA[0].observationId, state: 'reserved' }]));
  assert.notEqual(runner(['--inspect-session', '--session-id', a]).status, 0);
  fs.writeFileSync(path.join(dir, 'ledger.json'), JSON.stringify([{ sessionId: a, observationId: slotsA[0].observationId, state: 'completed' }]));
  assert.equal(JSON.parse(runner(['--inspect-session', '--session-id', a]).stdout).availableObservationIds.length, 9);
  assert.notEqual(runner(['R1', 'normal', '--session-id', a]).status, 0);
  assert.equal(fs.existsSync(path.join(dir, 'observations')), false);
  assert.deepEqual(historical.map(id => fs.readdirSync(path.join(tmp, id))), oldBefore);
  const preflight = cp.spawnSync(process.execPath, [path.join(root, 'preflight.cjs'), '--session-id', a, '--expected-head', head], { env: { ...process.env, ROBUSTNESS_RESULT_ROOT: tmp }, encoding: 'utf8' });
  assert.notEqual(preflight.status, 0);
  assert.equal(fs.readFileSync(path.join(dir, 'preflight.json'), 'utf8'), JSON.stringify(pre));
  assert.deepEqual(historical.map(id => fs.readdirSync(path.join(tmp, id))), oldBefore);
} finally { fs.rmSync(tmp, { recursive: true, force: true }); }
console.log('robustness session identity: PASS (provider/model calls 0)');
